{% set version = "2020.4" %}

package:
  name: python-tzdata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tzdata/tzdata-{{ version }}.tar.gz
  sha256: 233e2080c8d2f49dba97ab9b8da3742b212623ac273140b58cc9caa7764617f5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - tzdata

about:
  home: https://github.com/python/tzdata
  license: Apache-2.0
  license_file: LICENSE
  summary: Provider of IANA time zone data

  description: |
    This is a Python package containing zic-compiled binaries for the IANA time zone database.
    It is intended to be a fallback for systems that do not have system time zone data installed (or don't have it installed in a standard location),
    as a part of PEP 615.

extra:
  recipe-maintainers:
    - ocefpaf
    - pganssle
    - mbargull
