{% set version = "2024.2" %}

package:
  name: python-tzdata
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tzdata/tzdata-{{ version }}.tar.gz
  sha256: 7d85cc416e9382e69095b7bdf4afd9e3880418a2413feec7069d533d6b4e31cc

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - tzdata

about:
  home: https://github.com/python/tzdata
  license: Apache-2.0
  license_file: LICENSE
  summary: Provider of IANA time zone data

  description: |
    This is a Python package containing zic-compiled binaries for the IANA time zone database.
    It is intended to be a fallback for systems that do not have system time zone data installed (or don't have it installed in a standard location),
    as a part of PEP 615.

extra:
  recipe-maintainers:
    - ocefpaf
    - pganssle
    - mbargull
